
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    environment:
      REACT_APP_TESTMESS: $REACT_APP_TESTMESS
      REACT_APP_TESTMES: ${REACT_APP_TESTMES}
    steps:
      - run: 
        name: test
        command: |
          npm install
          npm start


