
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    environment:
      REACT_APP_TESTMESS: ${REACT_APP_TESTMESS}
      REACT_APP_TESTMES: ${REACT_APP_TESTMES}
    steps:
      - run: 
          name: install
          command: |
            npm install
            echo ${REACT_APP_TESTMES}
          environment:
            REACT_APP_TESTMESS: $REACT_APP_TESTMES
          
      - run: 
          name: start
          command: |
            echo "$REACT_APP_TESTMESS"