
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
          name: install
          command: |
            npm install
          
      - run: 
          name: start
          command: |
            npm run build
          environment:
            REACT_APP_TESTMESS: ${REACT_APP_TESTMESS}
            REACT_APP_TESTMES: ${REACT_APP_TESTMES}

      - run: 
          name: deploy
          command: |
            sudo yarn global add firebase-tools
            firebase use dev
            firebase deploy --token=${FIREBASE_TOKEN} --non-interactive

