
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    environment:
      REACT_APP_TESTMESS: ${REACT_APP_TESTMESS}
      REACT_APP_TESTMES: ${REACT_APP_TESTMES}
    steps:
      - checkout
      - run: 
          name: install
          command: |
            npm install
          
      - run: 
          name: start
          command: |
            npm run build

      - run: 
          name: deploy
          command: |
            sudo yarn global add firebase-tools
            firebase deploy --token ${FIREBASE_TOKEN}
