
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
          name: install
          command: |
            npm install
          
      - run: 
          name: start
          command: |
            echo 'export REACT_APP_TESTMESS="$REACT_APP_TESTMESS"' >> $BASH_ENV
            echo 'export REACT_APP_TESTMES="$REACT_APP_TESTMES"' >> $BASH_ENV
            npm run build
          
      - run: 
          name: deploy
          command: |
            sudo yarn global add firebase-tools
            firebase use dev
            firebase deploy --token=${FIREBASE_TOKEN} --non-interactive

